### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [butterproject/butter-android#10]
Here's how-to: https://f-droid.org/contribute/

**Comment by se-bastiaan** [comment]
If we're going for a store release then it'll be the Play Store. And I don't like conflicting packages that are not signed using our own key.

**Comment by pizzamaker** [comment]
Why not? It offers more security for your users, as F-Droid is a trusted distributor.

**Comment by se-bastiaan** [comment]
It offers more security than Google Play? Why?

**Comment by pizzamaker** [comment]
Google is a known PRISM collaborator, whereas F-Droid only deals with free software.

In any case, why not distribute through both channels? There are many users who actively avoid Google and would not be able to get this app in a safe manner without F-Droid packaging.

**Comment by se-bastiaan** [comment]
Security != Privacy

I'm not sure you have complete knowledge how publishing an usually application works, so:
Any Android application that is released, anywhere, should be signed. This is to prevent others from being able to update/release a modified version of the application. We will have our own generated key to sign the application package (APK) and then we can publish the application to the Play Store. (you can be sure it is our APK, since it is signed using our key).

The main F-Droid repository can contain any FOSS Android application (as long as it doesn't depend on non-FOSS libraries, which we actually currently do) but they won't not use _our_ key to sign the application package. This would cause collisions when users are using both F-Droid and any other source. That's annoying and I don't want that to happen.

The alternatives would then be:
1) Host our own F-Droid repository.
2) Host the application package on our website.

Since 2) will happen anyways I don't see any reason to execute 1). There are no real benefits.
