### ISSUE TITLE
No data on anime

### ISSUE THREAD

**Issue by gjimenezf** [butterproject/butter-android#103]
App Version:  0.2.8 arm64-v8a
Android version:  6.0.1

Expected behaviour: show anime shows
Actual behaviour: No data message

...

**Comment by streger** [comment]
We should check where do this come from in-app and request change there.
There are now few forks that probably still use our in-app bug report forms (links).
Se-bastiaan already changed it for this one here:
https://github.com/popcorn-official/popcorn-android/pull/39
but since he left it should be taken care of.

**Comment by xaiki** [comment]
let's close this one too so that we don't carry bugs that aren't ours.
